apiVersion: v1
kind: Service
metadata:
  name: mpo-frontend
  namespace: mpo
  labels:
    app: mpo-frontend
    service: mpo-frontend
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: mpo-frontend
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mpo-api-gateway-frontend
  namespace: mpo
  labels:
    account: mpo-frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mpo-frontend-v1
  namespace: mpo
  labels:
    app: mpo-frontend
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mpo-frontend
      version: v1
  template:
    metadata:
      labels:
        app: mpo-frontend
        version: v1
    spec:
      serviceAccountName: mpo-api-gateway-frontend
      containers:
      - name: mpo-frontend
        image: mpo-frontend:latest
        env:
        - name: MPO_BASE_PATH
          value: "frontend"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        securityContext:
          runAsUser: 1000
        